-- Создание таблицы users, если она не существует
CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL
);

-- Создание таблицы user_tasks_id, если она не существует
CREATE TABLE IF NOT EXISTS user_tasks_id
(
    user_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Создание таблицы user_vitrinas_id, если она не существует
CREATE TABLE IF NOT EXISTS user_vitrinas_id
(
    user_id    BIGINT NOT NULL,
    vitrina_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Вставка данных в таблицу users
INSERT INTO users (id, first_name, last_name, password)
SELECT 1, 'Ирина', 'Поливаева', '123456'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE id = 1);

INSERT INTO users (id, first_name, last_name, password)
SELECT 2, 'Сергей', 'Горячих', '123456'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE id = 2);