server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      platform: postgresql
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://dns-vitrina-db:5432/task_db
    username: root
    password: root