-- Создание таблицы tasks, если она не существует
CREATE TABLE IF NOT EXISTS tasks
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT,
    status       VARCHAR(50)  NOT NULL,
    created      DATE         NOT NULL,
    end_date     DATE,
    completed_at DATE,
    vitrina_id   BIGINT       NOT NULL
);

-- Создание таблицы task_user_ids для связи задач с пользователями, если она не существует
CREATE TABLE IF NOT EXISTS task_user_ids
(
    task_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE
);