-- Создание таблицы vitrinas, если она не существует
CREATE TABLE IF NOT EXISTS vitrinas
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(255) NOT NULL,
    x      INT,
    y      INT,
    width  INT,
    height INT
);

-- Создание таблицы vitrina_user_ids для связи витрин с пользователями, если она не существует
CREATE TABLE IF NOT EXISTS vitrina_user_ids
(
    vitrina_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    FOREIGN KEY (vitrina_id) REFERENCES vitrinas (id) ON DELETE CASCADE
);

-- Создание таблицы vitrina_task_ids для связи витрин с задачами, если она не существует
CREATE TABLE IF NOT EXISTS vitrina_task_ids
(
    vitrina_id BIGINT NOT NULL,
    task_id    BIGINT NOT NULL,
    FOREIGN KEY (vitrina_id) REFERENCES vitrinas (id) ON DELETE CASCADE
);

-- Вставка данных в таблицу vitrinas
INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 1, 1, 14, 275, 14, 'Телевизоры'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 1);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 2, 18, 0, 14, 270, 'Телефоны'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 2);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 3, 278, 45, 225, 14, 'Наушники справа'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 3);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 4, 68, 41, 90, 23, 'Телевизоры антенны'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 4);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 5, 135, 41, 90, 23, 'Колонки и саунд'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 5);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 6, 203, 41, 90, 23, 'Кабельки планшеты'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 6);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 7, 68, 171, 90, 23, 'Телевизоры маленькая снизу'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 7);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 8, 135, 171, 90, 23, 'Клавиатуры мыши'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 8);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 9, 203, 171, 90, 23, 'Ноутбуки'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 9);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 10, 278, 270, 57, 14, 'Флешки'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 10);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 11, 1, 288, 180, 14, 'Мониторы'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 11);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 12, 90, 297, 90, 23, 'Роутеры и принтеры'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 12);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 13, 144, 297, 86, 68, 'Кресла'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 13);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 14, 176, 423, 90, 23, 'Встройка и сплиты'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 14);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 15, 90, 423, 90, 23, 'Боллеры, контроллеры'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 15);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 16, 255, 426, 225, 18, 'КБТ стиралки'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 16);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 17, 176, 563, 135, 23, 'Бритвы и фены'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 17);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 20, 90, 563, 135, 23, 'Чайники, пылесосы вертикалки'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 20);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 21, 1, 468, 158, 14, 'Строительное'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 21);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 22, 1, 626, 113, 14, 'Пылесосы стационарные'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 22);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 23, 176, 738, 135, 23, 'Тостеры и КБТ газовые плиты'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 23);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 24, 90, 738, 135, 23, 'Блендеры и мультиварки'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 24);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 25, 255, 734, 315, 18, 'КБТ холодильники'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 25);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 26, 176, 923, 90, 23, 'Плиты и гладильные доски'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 26);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 27, 90, 923, 90, 23, 'Отпариватели и утюги'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 27);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 28, 1, 738, 176, 14, 'Микроволновки'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 28);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 29, 14, 914, 14, 54, 'Сушилки для овощей'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 29);

INSERT INTO vitrinas (id, y, x, width, height, name)
SELECT 30, 41, 1050, 18, 234, 'Встройка духовка и вытяжки'
WHERE NOT EXISTS (SELECT 1 FROM vitrinas WHERE id = 30);