version: '3.1'

volumes:
  pg_vitrina:

services:
  vitrina_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=vitrina_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
    volumes:
      - pg_vitrina:/var/lib/postgresql/data

    ports:
      - "127.0.0.1:5433:5432"